/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicareItems;

import ConnectionPack.SQLConnection;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class Ayurvedic extends javax.swing.JFrame {
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form Ayurvedic
     */
    public Ayurvedic() {
         this.setResizable(false);
        initComponents();
        AyurvedicData();
    }
    //    Display all the data into JTable
    public void AyurvedicData(){
            try(Connection con=SQLConnection.ConnectDB();){ 
            String sql="select Product_id,Product_Name,Company_Name,Mfg_Date,Exp_Date,Price,Quantity from products where Status='Ayurvedic'";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            Ayurvedic_Table.setModel(DbUtils.resultSetToTableModel(rs));
            }catch(Exception ex){
            ex.printStackTrace();
            }
    }
    
   public void clearall(){
    pname.setText("");
       cname.setText("");
       price.setText("");
       qut.setText("");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        addorg = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ayurvedic_Table = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        mfg = new com.toedter.calendar.JDateChooser();
        exp = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        qut = new javax.swing.JTextField();
        updateorg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ayurvedic");

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Ayurvedic Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Product Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Company Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Mfg Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, -1, 28));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Exp Date :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Price :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 286, -1, -1));

        pname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pnameKeyPressed(evt);
            }
        });
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 91, 153, 30));

        cname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnameKeyPressed(evt);
            }
        });
        jPanel1.add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 148, 153, 30));

        price.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceKeyPressed(evt);
            }
        });
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 282, 153, 30));

        addorg.setBackground(new java.awt.Color(51, 255, 0));
        addorg.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        addorg.setText("Add");
        addorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addorgActionPerformed(evt);
            }
        });
        jPanel1.add(addorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 393, -1, 38));

        clear.setBackground(new java.awt.Color(204, 255, 102));
        clear.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 40));

        Ayurvedic_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Company Name", "Mfg Date", "Exp Date", "Price", "Quantity", "Date & Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ayurvedic_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Ayurvedic_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Ayurvedic_Table);
        if (Ayurvedic_Table.getColumnModel().getColumnCount() > 0) {
            Ayurvedic_Table.getColumnModel().getColumn(7).setMinWidth(10);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 634, 464));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3d-home-icon-silver.gif"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        mfg.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(mfg, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 204, 153, -1));

        exp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 244, 153, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Quantity :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 334, -1, -1));

        qut.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        qut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qutKeyPressed(evt);
            }
        });
        jPanel1.add(qut, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 330, 153, 30));

        updateorg.setBackground(new java.awt.Color(153, 255, 153));
        updateorg.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        updateorg.setText("Update");
        updateorg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateorgActionPerformed(evt);
            }
        });
        jPanel1.add(updateorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       pname.setText("");
       cname.setText("");
       price.setText("");
       qut.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       Home h=new Home();
       h.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void addorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addorgActionPerformed
        if(pname.getText().equals("")||cname.getText().equals("")||price.getText().equals("")||qut.getText().equals("")){
         JOptionPane.showMessageDialog(this,"Please Enter All Data !");
          pname.grabFocus();
        } 
        else{ 
        String sql="Insert into Products(Product_Name,Company_Name,Mfg_Date,Exp_Date,Price,Quantity,Status) values(?,?,?,?,?,?,?)";
        try (Connection cn=SQLConnection.ConnectDB();){
            pst=cn.prepareStatement(sql);
            pst.setString(1, pname.getText());
            pst.setString(2, cname.getText());
            pst.setString(3,((JTextField)mfg.getDateEditor().getUiComponent()).getText());
            pst.setString(4, ((JTextField)exp.getDateEditor().getUiComponent()).getText());
            pst.setString(5, price.getText());
            pst.setString(6,qut.getText());
            pst.setString(7, "Ayurvedic");
            int r=pst.executeUpdate();
            if(r>0){
                JOptionPane.showMessageDialog(this, "Data Added in Table...");
            AyurvedicData();
            clearall();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
       } 
    }//GEN-LAST:event_addorgActionPerformed

    private void Ayurvedic_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Ayurvedic_TableMouseClicked
       int i=Ayurvedic_Table.getSelectedRow();
        TableModel m=Ayurvedic_Table.getModel();
        pname.setText(m.getValueAt(i, 1).toString());
        cname.setText(m.getValueAt(i, 2).toString());
        ((JTextField)mfg.getDateEditor().getUiComponent()).setText(m.getValueAt(i, 3).toString());
        ((JTextField)exp.getDateEditor().getUiComponent()).setText(m.getValueAt(i, 4).toString());
        price.setText(m.getValueAt(i, 5).toString());
        qut.setText(m.getValueAt(i, 6).toString());
    }//GEN-LAST:event_Ayurvedic_TableMouseClicked

    private void updateorgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateorgActionPerformed
      if(pname.getText().equals("")||cname.getText().equals("")||price.getText().equals("")||qut.getText().equals("")){
         JOptionPane.showMessageDialog(this,"Please Select The Table Row !");
          pname.grabFocus();
        } 
        else{
        int i=Ayurvedic_Table.getSelectedRow();
        String m = (Ayurvedic_Table.getModel().getValueAt(i, 0).toString());
        String sql="Update Products set Company_Name=?,Mfg_Date=?,Exp_Date=?,Price=?,Quantity=?where Product_Id="+m;
        try (Connection cn=SQLConnection.ConnectDB();){
            pst=cn.prepareStatement(sql);
            pst.setString(1, cname.getText());
            pst.setString(2,((JTextField)mfg.getDateEditor().getUiComponent()).getText());
            pst.setString(3, ((JTextField)exp.getDateEditor().getUiComponent()).getText());
            pst.setString(4, price.getText());
            pst.setString(5,qut.getText());
            int r=pst.executeUpdate();
            DefaultTableModel m1=(DefaultTableModel)Ayurvedic_Table.getModel();
            m1.setRowCount(0);
            if(r>0){
            JOptionPane.showMessageDialog(this, "Data Updated in Table...");
            AyurvedicData();
            clearall();
            }else{
            JOptionPane.showMessageDialog(this, "Error");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
      }
        
        
    }//GEN-LAST:event_updateorgActionPerformed

    private void pnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnameKeyPressed
         char c=evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            pname.setEditable(true);
        }else{
            pname.setEditable(false);
        }
    }//GEN-LAST:event_pnameKeyPressed

    private void cnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            cname.setEditable(true);
        }else{
            cname.setEditable(false);
        }
    }//GEN-LAST:event_cnameKeyPressed

    private void priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyPressed
       String ephno=price.getText();
        int len = ephno.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
          if(len<10){
             price.setEditable(true);
          }else{
              price.setEditable(false);
          }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                price.setEditable(true);
            }else{
               price.setEditable(false);    
            }
        }
    }//GEN-LAST:event_priceKeyPressed

    private void qutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qutKeyPressed
        String ephno=qut.getText();
        int len = ephno.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
          if(len<10){
             qut.setEditable(true);
          }else{
              qut.setEditable(false);
          }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                qut.setEditable(true);
            }else{
               qut.setEditable(false);    
            }
        }
    }//GEN-LAST:event_qutKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayurvedic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayurvedic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayurvedic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayurvedic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ayurvedic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ayurvedic_Table;
    private javax.swing.JButton addorg;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cname;
    private com.toedter.calendar.JDateChooser exp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser mfg;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qut;
    private javax.swing.JButton updateorg;
    // End of variables declaration//GEN-END:variables
}
