/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicareItems;
import ConnectionPack.SQLConnection;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Patient extends javax.swing.JFrame {
PreparedStatement pst=null;

    /**
     * Creates new form Patient
     */
    public Patient() {
         this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dnm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        payment = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        dis = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Please Fill Following Information");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Patient Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 80, -1, -1));

        paname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        paname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panameKeyPressed(evt);
            }
        });
        jPanel1.add(paname, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 77, 163, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Phone Number :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 80, -1, -1));

        phno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        phno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phnoKeyPressed(evt);
            }
        });
        jPanel1.add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 77, 163, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Doctor Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 150, -1, -1));

        dnm.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dnm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dnmKeyPressed(evt);
            }
        });
        jPanel1.add(dnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 147, 163, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("City :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 159, -1, -1));

        city.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityKeyPressed(evt);
            }
        });
        jPanel1.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 156, 163, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Patient Disease :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 242, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Total Price :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 318, -1, -1));

        tot.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totKeyPressed(evt);
            }
        });
        jPanel1.add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 315, 163, -1));

        clear.setBackground(new java.awt.Color(153, 153, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 409, 137, 38));

        payment.setBackground(new java.awt.Color(51, 255, 0));
        payment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        payment.setText("Payment");
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        jPanel1.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 409, 159, 38));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3d-home-icon-silver.gif"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dis.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                disKeyPressed(evt);
            }
        });
        jPanel1.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 239, 163, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Home  h=new Home();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
      String sql="insert into patient(Patient_Name,Phone_Number,Doctor_Name,City,Disease,Total_Price) values(?,?,?,?,?,?)";
        try(Connection cn=SQLConnection.ConnectDB();) {
            pst=cn.prepareStatement(sql);
            
            pst.setString(1, paname.getText());
            pst.setString(2, phno.getText());
            pst.setString(3, dnm.getText());
            pst.setString(4, city.getText());
            pst.setString(5, dis.getText());
            pst.setString(6, tot.getText());
            
            int r=pst.executeUpdate();
            if(r>0){
                JOptionPane.showMessageDialog(this,"Data Saved Successfully...");
                Bill b=new Bill();
                Bill.patnm.setText(this.paname.getText());
                Bill.pno.setText(this.phno.getText());
                Bill.pay.setText(this.tot.getText());
                b.setVisible(true);
                this.setVisible(false);
            }else{
            
                JOptionPane.showMessageDialog(this, "Data Not Saved....");
            }
        } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, e);
        }
        
        
        
        
        
                      
    }//GEN-LAST:event_paymentActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       paname.setText("");
       phno.setText("");
       dnm.setText("");
       city.setText("");
       dis.setText("");
       tot.setText("");
               
    }//GEN-LAST:event_clearActionPerformed

    private void panameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            paname.setEditable(true);
        }else{
            paname.setEditable(false);
        }
    }//GEN-LAST:event_panameKeyPressed

    private void phnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phnoKeyPressed
        // TODO add your handling code here:
         String ephno=phno.getText();
        int len = ephno.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
          if(len<10){
             phno.setEditable(true);
          }else{
              phno.setEditable(false);
          }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                phno.setEditable(true);
            }else{
               phno.setEditable(false);    
            }
        }
    }//GEN-LAST:event_phnoKeyPressed

    private void dnmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dnmKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            dnm.setEditable(true);
        }else{
            dnm.setEditable(false);
        }
    }//GEN-LAST:event_dnmKeyPressed

    private void cityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            city.setEditable(true);
        }else{
            city.setEditable(false);
        }
    }//GEN-LAST:event_cityKeyPressed

    private void disKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_disKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)|| Character.isWhitespace(c)|| Character.isISOControl(c)){
            dis.setEditable(true);
        }else{
            dis.setEditable(false);
        }
    }//GEN-LAST:event_disKeyPressed

    private void totKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totKeyPressed
        // TODO add your handling code here:
         String ephno=tot.getText();
        int len = ephno.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
          if(len<10){
             tot.setEditable(true);
          }else{
              tot.setEditable(false);
          }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                tot.setEditable(true);
            }else{
               tot.setEditable(false);    
            }
        }
    }//GEN-LAST:event_totKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JButton clear;
    private javax.swing.JTextField dis;
    private javax.swing.JTextField dnm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField paname;
    private javax.swing.JButton payment;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField tot;
    // End of variables declaration//GEN-END:variables
}
